version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: laravel_myshop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: myshop
      MYSQL_USER: alexandr
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
